language: python
dist: xenial
sudo: true
python:
# - "3.5"
# - "3.6"
  - "3.7"
before_install:
  - sudo apt-get install -y libgirepository1.0-dev
install:
  - pip install pyqt5
  - pip install cairo
  - pip install pygobject
  - pip install .
  - pip install coverage
  - pip install python-coveralls
script:
  - export ASYNCFRAMES_SRC=`python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/asyncframes
  - cd test
  - xvfb-run python3 -m coverage run --source=$ASYNCFRAMES_SRC test_asyncframes.py
after_success:
  - coveralls