language: python
dist: xenial
sudo: true
python:
# - "3.5"
# - "3.6"
  - "3.7_with_system_site_packages"
before_install:
  - sudo apt-get install --no-install-recommends -y xvfb gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-pep8 pyflakes python3-pytest
install:
  - pip install pyqt5
  - pip install pycairo
  - pip install pygobject
  - pip install .
  - pip install coverage
  - pip install python-coveralls
script:
  - export ASYNCFRAMES_SRC=`python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/asyncframes
  - cd test
  - xvfb-run python3 -m coverage run --source=$ASYNCFRAMES_SRC test_asyncframes.py
after_success:
  - coveralls