language: python
dist: xenial
sudo: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pyqt5
  - pip install .
  - pip install coverage
  - pip install python-coveralls
script:
  - cd test; xvfb-run python3 -m coverage run test_asyncframes.py
after_success:
  - python3 -m coveralls