language: python
dist: xenial
sudo: true
python:
# - "3.5"
# - "3.6"
  - "3.7"
install:
  - pip install pyqt5
  - pip install .
  - pip install coverage
  - pip install python-coveralls
script:
  - export ASYNCFRAMES_SRC=`pwd`/asyncframes
  - cd test
  - xvfb-run python3 -m coverage run --source=$ASYNCFRAMES_SRC test_asyncframes.py
after_success:
  - coveralls